### PR TITLE
Review changes from meeting 2022-01-18

### PR DESCRIPTION
**Pull request by gudmundurjon**

### CODE REVIEW

**Review by siggauti — CHANGES_REQUESTED** [review]
ClosingDate:  Date when the claim was paid or cancelled 
claim is not closed if transferred between primary and secondary

**Comment by asgeirh** [comment]
### Issues
https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L29
* I was under the impressions the banks did not want the additionalDepositAccounts in the list
* customerNumberTemplate is missing from the template.  I know Landsbankinn does not support it but all other banks do.  Can't Landsbankinn skip it and others have it?

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L655
* Missing status of the batch
* Return from get batch seems wrong to me.  Why are we getting the entire batch back.  We only need to get the status of the batch and result.  I think it should be
```json
{
	"batchId": "stringstringstringstringstringstring",
        "batchStatus": "completeWithErrors"
	"success": 2,
	"failed": 1,
	"pending": 0,
	"actionType": "create",
	"actions": {
		"successes": [{
				"claimKey": {
					"claimantId": "0208715009",
					"account": "000126123456",
					"dueDate": "2022-01-31"
				},
				"directPaymentClaim": false
			},
			{
				"claimKey": {
					"claimantId": "0208715009",
					"account": "000126123456",
					"dueDate": "2022-01-31"
				},
				"directPaymentClaim": true
			}
		],
		"errors": [{
			"claimKey": {
				"claimantId": "0208715009",
				"account": "000126123456",
				"dueDate": "2022-01-31"
			},
			"error": {
				"code": "1000",
				"message": "Duplicate claim creation"
			}
		}]
	}
}
```

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L149
and
https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L445
* The following fields are **missing**
** SecondaryCollectionTemplateCode
** SecondaryCollectionClaimTemplateId
** CategoryCode
** TotalAmountDue
** NoticeChargeAmount
** DefaultChargeAmount
** OtherCostsAmount
** OtherDefaultCostsAmount
** DefaultInterestAmount
** IsPartiallyPaid
* There is extra currency on main object.  Its duplicate of **amount->currency**
* referenceRate should be moved into **amount**
* 

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L470
* Is this the current templateCode or primaryTemplateCode or secondaryTemplateCode.  If its only primaryTemplateCode then should we not have also secondaryTemplateCode?

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L205
* Is it possible to patch the collectionState?

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L270
* Missing the following attibutes
** claimTemplateId from the payment
** secondaryTemplateCode of payment
* I think we should rename valueDate to ajustedInterestDate.  If this value is specified it says what date was used for calculating interest to.

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L327
* Missing the field transactionTimestamp

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L531
* How can we see if the claim is set in directDebit?

https://github.com/stadlar/IST-FUT-FMTH/blob/7827bc7d74e833fff0ec1349e098820a2207cb2b/Vinnusv%C3%A6%C3%B0i/Verk%C3%BE%C3%A1ttur%204/IOBWS-Claims3.0.yaml#L594
* How is the action type specified?  If you want to create/alter claims?  I assume cancel and recreate are infact alters.


### Features
* Is it possible to get a unique id on the payment item?  Today I use complicated query for matching that could break easly
** If that payment could be matched to the payment on account even better ;)

**Comment by gudmundurjon** [comment]
Printing needs to be added back to the claim.

**Comment by gudmundurjon** [comment]
Patch reworked according to Asgeir comment. Missing fields added and amount, value and % presented as double.

**Pull request merged**
